Add major sync from chezmoi
Including:
- nix related config
- other new config
- scripts using `jq`
- pacman log

diff --git a/bin/env-tl b/bin/env-tl
--- a/bin/env-tl
+++ b/bin/env-tl
@@ -9,8 +9,10 @@ called_as=$(basename "$0")
 
 miktex_path_grep=miktex
 
-if [[ "$(echo "$PATH" | wc -l)" -eq 1 ]];  # sanity check
-then
+if [[ "$(echo "$PATH" | wc -l)" -ne 1 ]]; then
+    >&2 echo '## invalid PATH, please check!'
+    exit 1
+else
     PATH=$( \
         tr ':' '\n' <<< "$PATH" \
         | grep -v "$miktex_path_grep" \
